name: Deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Noop
        run: exit 0

  plan:
    name: Plan
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Add plan
        run: |
          echo "# Deployment Plan" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Change A" >> $GITHUB_STEP_SUMMARY
          echo "- Change B" >> $GITHUB_STEP_SUMMARY
          echo "- Change C" >> $GITHUB_STEP_SUMMARY

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    needs: plan
    steps:
      - name: Noop
        run: exit 0
